record_video: yes
logging: True

environment:
  render: True
  # just testing commenting
  evaluate: False
  determine_env: 0  # 0: not determine / 1: circle / 2: box / 3: corridor
  num_envs: 500
  max_n_update: 30000
  eval_every_n: 100
  new_environment_every_n: 50
  seed:
    train: 0
    evaluate: 600
  num_threads: 12
  test_num_threads: 2
  simulation_dt: 0.0025
  control_dt: 0.01
  max_time: 6.0
  command_period: 0.02
  obstacle_grid_size:
    min: 2.5
    max: 5.0
  corridor_short_width:
    min: 2.0
    max: 6.0
  n_rewards: 4
  reward:
    goal_distance:  # (+)
      coeff: 10.0
    traversal_distance:  # (-)
      coeff: 0.0
    goal_terminate:  # (+)
      coeff: 1.0
    obstacle_terminate:  # (-)
      coeff: 0.05
  command:
    forward_vel:
      min: -1.0
      max: 1.0
    lateral_vel:
      min: -0.4
      max: 0.4
    yaw_rate:
      min: -1.2
      max: 1.2
  randomization: False  # 1) Base COM position, 2) Mass of links, 3) Joint position
  random_initialize: True  # used for training
  random_external_force: False  # 50N force for 1s for lateral direction
  point_goal_initialize: False  # used for evaluating

training:
  learning_rate: 5e-4
  num_learning_epochs: 4
  num_mini_batches: 6
  gamma: 0.997
  lamda: 0.95
  entropy_coef: 0.0
  shuffle_batch: True

architecture:
  use_latent_state: False
  state_encoder: # state = lidar + (encoded COM history)
    input: 450  # COM_encoder output is included in the input  (360 + 32)
    output: 100
    shape: [ 256, 256, 128, 128 ]
    activation: leakyrelu
    dropout: 0.2
    batchnorm: True
  policy_net: [256, 128]
  value_net: [256, 128]
  command_tracking_policy_net: [128, 128]
